"use client"

import React, { useState } from 'react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UpperBar } from '../../../components/ui/UpperBar/UpperBar'
import '../../globals.css'
import { ProfilePicture } from '@/components/ui/ProfilePicFrame/ProfilePicture'
import { GenericPost } from '@/components/ui/Generic_post/GenericPost'
import classes from './MyProfile.module.css'
import { MiddleBar } from '@/components/ui/MiddleBar/MiddleBar'
import { useRouter } from 'next/navigation';
import { UserProfile } from '@/components/ui/UserProfile/userprofile'
import { useSession } from 'next-auth/react';
// import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function DraftPage({
  children,
}: {
  children: React.ReactNode
}) {
  const session = useSession();
  console.log("Name: ")
  console.log(session.data?.user.name)
  console.log("Nickname: ")
  console.log(session.data?.user.nickName)

  return (

    <html lang="pt-br" style={{height: '100%'}}>

    <body   className={inter.className}
            style = {{backgroundColor: 'var(--background-color)', height: '100%'}}>
        {children}
        
        <UpperBar text="Meu perfil" />
        <section style={{position: 'relative', height :  '40%', top : '15%'}}>
          <UserProfile userName='lucas' nickName='luke' numFollow={10} numFollowers={10} numPosts={1}/>
          <MiddleBar/>
        </section>

        <section style = {{position: 'relative', height: '100%', top: '15%'}} >
          <GenericPost text = 'Text1' n_likes={0} n_comm={0}/>
          <GenericPost text = 'Text2' n_likes={0} n_comm={0}/>
        </section>
   
    </body>

    </html>

  )
}

// const Bla = () => {
//   return(
//     <section>
//       <button onClick={()=> console.log("Clicou")}>

//       </button>
//     </section>
//   )
// }
// export default Bla;