import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UpperBar } from '../../components/ui/UpperBar/UpperBar'
import '../globals.css'
import { ProfilePicture } from '@/components/ui/ProfilePicFrame/ProfilePicture'
import { GenericPost } from '@/components/ui/Generic_post/GenericPost'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DraftPage({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" style={{height: '100%'}}>
    <body   className={inter.className}
            style = {{backgroundColor: 'var(--background-color', height: '100%'}}>
        {children}
        <UpperBar text="Meu perfil">
        </UpperBar>
        <section style={{position: 'relative', height: '50%'}}>
            <ProfilePicture marginTop = "40%" left = "5%" scale = "20%">
            </ProfilePicture>
        </section>
        <div style={{position: 'relative', height: '8%', backgroundColor: 'white'}}></div>
        <GenericPost></GenericPost>
        <GenericPost></GenericPost>
    </body>
    </html>
  )
}